// Generated by scripts/generate-widget-questions.js — do not edit by hand.
// 38 questions bundled into the widget so it needs no app data.

struct WidgetQuestion {
    let id: String
    let title: String
    let category: String
    let difficulty: String
}

let ALL_QUESTIONS: [WidgetQuestion] = [
    WidgetQuestion(id: "design-netflix-for-kids", title: "Design Netflix for Kids", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "design-parking-features-google-maps", title: "How would you design parking features for Google Maps?", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "design-recommendation-system-ecommerce", title: "Design a recommendation system experience for an e-commerce app", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "design-zepto-cart-abandonment-checkout", title: "Design a feature for Zepto to reduce cart abandonment among users who add items but never check out", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "favorite-product-duolingo", title: "What is your favorite product? (Duolingo)", category: "Product Design", difficulty: "Easy"),
    WidgetQuestion(id: "app-critique-linkedin-job-application-flow", title: "Critique LinkedIn's job application flow — identify the top 3 friction points and how you'd fix each", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "critique-linkedin-onboarding-new-graduates", title: "Critique LinkedIn's onboarding flow for new graduates — what's broken, what works, and your top 3 fixes", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "swiggy-international-expansion-strategy", title: "Create a 1-year strategy (Now/Next/Later) for Swiggy's international expansion", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "whatsapp-monetization-strategy", title: "Design a WhatsApp monetization strategy — no ads, and no extension of current offerings (no business messaging, UPI, or stores)", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "how-would-you-10x-duolingo", title: "How would you 10x Duolingo?", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "position-notion-vs-confluence-google-docs", title: "How would you position Notion vs. its alternatives (Confluence + Google Docs)?", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "monetization-price-package-uber-swiggy", title: "How would you price and package a product? (Uber Mobility + Swiggy Food Delivery)", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "competitor-cheaper-spotify-instagram", title: "A competitor launched the same feature cheaper. What do you do? (Spotify + Instagram)", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "enter-new-market-apple-ai-llms", title: "Should we enter a new market/vertical? How do you decide? (Apple entering AI/LLMs)", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "meta-reels-invest-strategy-metrics", title: "You're a PM at Meta. Why should Meta continue investing in Reels, and what goals and metrics would you set?", category: "Product Strategy", difficulty: "Medium"),
    WidgetQuestion(id: "guesstimate-ride-hailing-trips-bangalore-monday", title: "Estimate the total number of ride-hailing trips completed in Bangalore on a typical Monday", category: "Guesstimate", difficulty: "Medium"),
    WidgetQuestion(id: "guesstimate-blinkit-grocery-orders-delhi-sunday", title: "Estimate the number of grocery orders placed on Blinkit in Delhi-NCR on a Sunday morning (6am-12pm)", category: "Guesstimate", difficulty: "Medium"),
    WidgetQuestion(id: "guesstimate-uber-rides-mumbai-weekday-morning", title: "Estimate the number of Uber rides taken in Mumbai on a weekday morning (7-10 AM)", category: "Guesstimate", difficulty: "Medium"),
    WidgetQuestion(id: "guesstimate-restaurants-in-bengaluru", title: "Estimate the number of restaurants in Bengaluru, India", category: "Guesstimate", difficulty: "Medium"),
    WidgetQuestion(id: "design-trust-layer-enterprise-ai", title: "Design the 'trust' layer for enterprise AI output", category: "AI", difficulty: "Hard"),
    WidgetQuestion(id: "design-feedback-mechanism-ema-corrections", title: "Design a feedback mechanism that improves the AI from user corrections", category: "AI", difficulty: "Hard"),
    WidgetQuestion(id: "nsm-ai-legal-document-reviewer-smbs", title: "You're PM at a startup building an AI-powered legal document reviewer for Indian SMBs. Define your North Star metric and defend it.", category: "AI", difficulty: "Medium"),
    WidgetQuestion(id: "nsm-ai-sales-email-assistant-gaming", title: "You're a PM at a startup building an AI-powered sales email assistant. Define your North Star metric and how you'd prevent gaming it.", category: "AI", difficulty: "Medium"),
    WidgetQuestion(id: "nsm-ai-email-assistant-sales-quality", title: "You're a PM at a B2B SaaS startup building an AI email assistant for sales teams. What's your North Star metric and how do you measure AI quality?", category: "AI", difficulty: "Medium"),
    WidgetQuestion(id: "rca-support-agent-resolution-drop", title: "Customer-support agent resolution dropped from 70% to 55% over two weeks. Diagnose it.", category: "RCA", difficulty: "Hard"),
    WidgetQuestion(id: "rca-recruiting-candidate-quality-model-update", title: "Recruiting candidate quality dropped after a model update. Diagnose the failure mode.", category: "RCA", difficulty: "Hard"),
    WidgetQuestion(id: "rca-aov-drops-18-percent-wow", title: "Average order value on your e-commerce platform drops 18% week-over-week. How do you diagnose and address it?", category: "Analytical", difficulty: "Medium"),
    WidgetQuestion(id: "measure-success-zepto-buy-again-shortcut", title: "How would you measure the success of a new 'Buy Again' shortcut on Zepto's home screen?", category: "Analytical", difficulty: "Medium"),
    WidgetQuestion(id: "measure-success-meesho-video-shopping", title: "How would you measure the success of Meesho's newly launched in-app video shopping feature?", category: "Analytical", difficulty: "Medium"),
    WidgetQuestion(id: "q-zomato-buy-again-metrics", title: "How would you measure the success of a new 'Buy again' shortcut on Zomato's home screen?", category: "Analytical", difficulty: "Medium"),
    WidgetQuestion(id: "q-meesho-first-buyer", title: "Design a feature for Meesho to help first-time buyers in Tier 3 cities who browse but never complete their first purchase", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "q-zepto-cart-abandonment", title: "Design a feature for Zepto to reduce cart abandonment caused by out-of-stock items at checkout", category: "Product Design", difficulty: "Medium"),
    WidgetQuestion(id: "q-ubereats-growth", title: "How would you grow UberEats' user base?", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "q-uber-monetization", title: "How would you price and package Uber Mobility?", category: "Product Strategy", difficulty: "Hard"),
    WidgetQuestion(id: "q-ema-north-star", title: "Define the North Star metric for an AI Employee product like Ema", category: "Analytical", difficulty: "Hard"),
    WidgetQuestion(id: "q-ema-hitl", title: "Design the human-in-the-loop system for Ema: when should it act autonomously vs. ask?", category: "Product Design", difficulty: "Hard"),
    WidgetQuestion(id: "q-amazon-reviews-abuse", title: "Design a system to track and reduce review abuse on Amazon", category: "Product Design", difficulty: "Hard"),
    WidgetQuestion(id: "q-ema-hallucination-rca", title: "Hallucination complaints spiked from one client. Nothing changed in the product. RCA.", category: "Analytical", difficulty: "Hard"),
]
