// Generated by scripts/generate-narration.js — do not edit by hand.
// One narration track per highlighted drill; chapters map moments in the
// audio to the sections of the answer.

export interface NarrationChapter {
  label: string;
  /** Start of this chapter in seconds. */
  at: number;
}

export interface Narration {
  source: number; // static require() of the bundled mp3
  duration: number;
  chapters: NarrationChapter[];
}

export const NARRATION: Record<string, Narration> = {
  'position-notion-vs-confluence-google-docs': {
    source: require('../../assets/narration/position-notion-vs-confluence-google-docs.mp3'),
    duration: 250,
    chapters: [{"label":"The question","at":0},{"label":"The framework","at":20.6},{"label":"Clarify first","at":56.8},{"label":"Who it is for — and not","at":84.6},{"label":"The category decision","at":120},{"label":"The structural gap","at":151.7},{"label":"The statement","at":183.8},{"label":"Proof and metrics","at":212.4}],
  },
  'q-zomato-buy-again-metrics': {
    source: require('../../assets/narration/q-zomato-buy-again-metrics.mp3'),
    duration: 217,
    chapters: [{"label":"The question","at":0},{"label":"The framework","at":21.5},{"label":"Clarify first","at":55.6},{"label":"The North Star","at":79.4},{"label":"Supporting metrics","at":113.2},{"label":"Counter-metrics","at":144.3},{"label":"The decision rule","at":175.8}],
  },
  'design-netflix-for-kids': {
    source: require('../../assets/narration/design-netflix-for-kids.mp3'),
    duration: 224,
    chapters: [{"label":"The question","at":0},{"label":"The framework","at":18.5},{"label":"Clarify first","at":42.1},{"label":"Two users, one product","at":74.7},{"label":"Prioritise","at":109.6},{"label":"The bet","at":139.7},{"label":"Metrics and the trade-off","at":177.5}],
  },
};
